title: Ryan Miller
logo: "/images/head_shot_smile.jpg?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello World! I am a grad student in Georgia Tech's Master of Science in Analytics program and am interested in Deep Learning applications in Image Recognition and Computer Vision.  
  <br><br>
  <a href="https://www.linkedin.com/in/ryan-miller-93a588139/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
